# standard jekyll configuration

permalink: pretty
markdown: rdiscount 
auto: true
baseurl: 

# configuration required for some pages

domain: http://scottweinstein.github.com
title: A checklist for personal data safety
author: Scott Weinstein
email: scottwww@squidnet.com

# configuration for ehancements, uncomment to enable

feedburner:
   id: AChecklistForPersonalDataSafety

google_analytics:
   account: UA-27918472-1

github:
   username: ScottWeinstein

disqus:
   id: computersafety
